### ISSUE TITLE
Many relative file paths are wrong

### ISSUE THREAD

**Issue by bernie-g** [Blockception/Minecraft-bedrock-json-schemas#1]
Hey, I'm attempting to use these schemas to create classes in C# using quicktype. However, it seems that a lot of relative paths are incorrect. For example `/behaviour/entities/1.16.0/components/minecraft.breedable.json#/properties/breed_items/oneOf/0/items` refers to `../../../../general/item/identifier.json`, which is not correct. It should be `../../../general/item/identifier.json` instead. I started fixing them one by one but gave up after like 15 because I have no idea how many more there will be.

Any ideas why this could be the case? Otherwise this looks like a great project!

**Comment by bernie-g** [comment]
Okay I managed to go through and fix all the file path errors, but now quicktype still wont build the classes because of this error:
`Error: Trying to make an empty union - do you have an impossible type in your schema?`. There's no stacktrace attached either, so I'm not sure what could be causing that. I don't know if you've used quicktype so it may be hard to debug.

**Comment by DaanV2** [comment]
Hey,

So unfortunately all these relative paths are actually correct, for vscode :/
If they weren't vscode would give me a lot of errors.

Recently also vscode has a bug where relative file path has been going wrong and I had to do some quick fixes:

All these files are temporary and need to be ignored.
https://github.com/Blockception/Minecraft-bedrock-json-schemas/commit/4ff719353ae105b0b8bc9204d37ed3fb3f784b95

The issue in itself:
https://github.com/Blockception/Minecraft-bedrock-json-schemas/issues/1#issuecomment-755014744


On the reason why quicktype might be failing, I have some ideas. but I'm not experienced in quicktype so it's all guesses.

Because of some polymorphous structures, I use allot of "anyof", "oneof" schema properties which allows me to switch between string and numbers for example (molang) 

But these all change between object/arrays and so on.
There is also a problem of recursiveness. Filters and entities events have designed as quite recursive structure, 

or event polymorphous object that chain recursive.

**Comment by DaanV2** [comment]
If it helps, I am writing a json schema compressor, 

This is the code I use for solving the paths
https://github.com/DaanV2/JsonSchemaValidationCompressor.Net/blob/7626e192280f8b204fc8dceabb3737b5f691a702/JsonSchemaValidationCompressor.Net%20-%20Source/Classes/SchemaResolver/SchemaResolver%20-%20Resolve.cs#L101

**Comment by bernie-g** [comment]
Okay, thank you. As far as the unions, I've used several other very large bedrock schemas with quicktype  before and it's created the union types just fine so I'm pretty sure it's something specific to this one. I guess I can't really debug it because quicktype doesn't give me a stacktrace. Anyway thanks for the help!

I think the vscode link you sent is the wrong link btw.

**Comment by bernie-g** [comment]
@DaanV2 Just wanted to let you know that I finally got this to work. I ran it through your compressor which fixed the relative file path issue easily. After that I spent like 2 hours doing a binary search through the whole schema to figure out what was breaking it. Turns out it's this random definition:
```json
    "CJDFDDDHFC": {
      "type": "string",
      "title": "The minecraft item identifier 1.8.0",
      "description": "The minecraft item identifier",
      "pattern": "^[0-9a-zA-Z:_\\-\\.]+$"
    }
```

It's only used in one spot, behavior.snacking, and I'm quite sure I'm never gonna use that so I'm just removing it. Thanks for the help!
