### ISSUE TITLE
Many titles are wrong

### ISSUE THREAD

**Issue by bernie-g** [Blockception/Minecraft-bedrock-json-schemas#2]
Hey, I'd like to use this schema in my project but at the moment it's kind of unusable because the title fields should really be descriptions. Most schema parsers use the title field as the type name, so when the title is `The minecraft item identifier 1.8.0`, the generated type name is `TheMinecraftItemIdentifier180`, which is less than ideal. I'm not sure if this is on purpose or if it was done by some automated tool, but it should probably be "ItemIdentifier" or something instead. I'm creating this issue to make sure there's not a good reason for this, and if there's not then I'll start fixing them + make a PR. Let me know!

**Comment by DaanV2** [comment]
It's all done under good reason, and slightly yes an automated too was used. 

It's not something I want to be changed. maybe for spelling or capitalisation yes. 

But it marks for example if the definition is for example not documented, usually comes along with UNDOCUMENTATED in either the title or description.

The version numbering that is shown is important for me to figure out when something is used.

Behaviors for example while having different formats. Still can refer to 1.8.0 components as they have never changed since their creation. A good example of changed components is the "Minecraft:damage_sensor" that changes somewhere in version 1.10.0 - 1.12.0. And I can see on the title of the component in the file itself how it's constructing the schema.

**Comment by bernie-g** [comment]
Okay, no worries, I'll just change them locally then. Thanks!
